# -*- coding: utf-8 -*-
"""fgcriss

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rXQXZHGPyx7TxetLO8PmUW3vIDzlt693
"""

import math
import datetime
from abc import ABC, abstractmethod


class Color:
    def __init__(self, color):
        self.__color = None
        self.color = color

    @property
    def color(self):
        return self.__color

    @color.setter
    def color(self, value):
        if isinstance(value, str) and value.strip():
            self.__color = value
        else:
            raise ValueError("El color debe ser una cadena de texto no vacía.")

    def __str__(self):
        return f"Color: {self.__color}"


class FiguraGeometrica(ABC):
    def __init__(self, alto, ancho):
        self.__alto = None
        self.__ancho = None
        self.alto = alto
        self.ancho = ancho

    @property
    def alto(self):
        return self.__alto

    @alto.setter
    def alto(self, value):
        if isinstance(value, (int, float)) and value > 0:
            self.__alto = float(value)
        else:
            raise ValueError("El alto debe ser un número positivo.")

    @property
    def ancho(self):
        return self.__ancho

    @ancho.setter
    def ancho(self, value):
        if isinstance(value, (int, float)) and value > 0:
            self.__ancho = float(value)
        else:
            raise ValueError("El ancho debe ser un número positivo.")

    @abstractmethod
    def area(self):
        pass

    @abstractmethod
    def perimetro(self):
        pass

    def __str__(self):
        return f"Alto: {self.__alto}, Ancho: {self.__ancho}"


class Rectangulo(FiguraGeometrica, Color):
    def __init__(self, alto, ancho, color):
        FiguraGeometrica.__init__(self, alto, ancho)
        Color.__init__(self, color)

    def area(self):
        return self.alto * self.ancho

    def perimetro(self):
        return 2 * (self.alto + self.ancho)

    def __str__(self):
        return f"Rectángulo -> {FiguraGeometrica.__str__(self)}, {Color.__str__(self)}"


class Cuadrado(FiguraGeometrica, Color):
    def __init__(self, lado, color):
        FiguraGeometrica.__init__(self, lado, lado)
        Color.__init__(self, color)

    @property
    def alto(self):
        return super().alto

    @alto.setter
    def alto(self, value):
        FiguraGeometrica.alto.fset(self, value)
        FiguraGeometrica.ancho.fset(self, value)

    @property
    def ancho(self):
        return super().ancho

    @ancho.setter
    def ancho(self, value):
        self.alto = value

    def area(self):
        return self.alto * self.ancho

    def perimetro(self):
        return 4 * self.alto

    def __str__(self):
        return f"Cuadrado -> Lado: {self.alto}, {Color.__str__(self)}"


class Circunferencia(FiguraGeometrica, Color):
    def __init__(self, diametro, color):
        FiguraGeometrica.__init__(self, diametro, diametro)
        Color.__init__(self, color)

    @property
    def alto(self):
        return super().alto

    @alto.setter
    def alto(self, value):
        FiguraGeometrica.alto.fset(self, value)
        FiguraGeometrica.ancho.fset(self, value)

    @property
    def ancho(self):
        return super().ancho

    @ancho.setter
    def ancho(self, value):
        self.alto = value

    def area(self):
        radio = self.alto / 2.0
        return math.pi * (radio ** 2)

    def perimetro(self):
        return math.pi * self.alto

    def __str__(self):
        return f"Circunferencia -> Diámetro: {self.alto}, {Color.__str__(self)}"


def sumar_areas(figuras_geometricas):
    suma = 0
    for figura in figuras_geometricas:
        suma += figura.area()
    return suma


def sumar_perimetros(figuras_geometricas):
    suma = 0
    for figura in figuras_geometricas:
        suma += figura.perimetro()
    return suma


if __name__ == "__main__":
    now = datetime.datetime.now()
    fecha_hora_str = now.strftime('%Y-%m-%d %H:%M:%S')
    print(f"--- Ejecución del Código - {fecha_hora_str} ---\n")

    lista_figuras = []

    lista_figuras.append(Cuadrado(5, 'Rojo'))
    lista_figuras.append(Rectangulo(alto=10, ancho=15, color='Rojo'))
    lista_figuras.append(Circunferencia(diametro=8, color='Azul'))

    print("--- Demostración Individual de Figuras ---")
    for fig in lista_figuras:
        print(fig)
        print(f"  Área: {fig.area():.2f} | Perímetro: {fig.perimetro():.2f}\n")

    print("--- Demostración de Funciones Polimórficas ---")
    print(f"Suma Total de Áreas: {sumar_areas(lista_figuras):.2f}")
    print(f"Suma Total de Perímetros: {sumar_perimetros(lista_figuras):.2f}\n")

    print("--- Demostración de Validaciones Estrictas (__) ---")
    try:
        print("Creando rectángulo con alto negativo...")
        Rectangulo(-8, 15, 'Verde')
    except ValueError as e:
        print(f"ERROR ATRAPADO: {e}")

    try:
        print("\nModificando el color del cuadrado a una cadena vacía...")
        lista_figuras[0].color = "   "
    except ValueError as e:
        print(f"ERROR ATRAPADO: {e}")

    print(f"\n--- Fin de la Demostración - {fecha_hora_str} ---")